In [1]:
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from nltk.stem import RSLPStemmer
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
import pandas as pd
import nltk
from sklearn.pipeline import Pipeline

In [2]:
nltk.download('stopwords')
stop_words = set(stopwords.words('portuguese'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\janna\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [3]:
df = pd.read_csv('../data/Pfizer.csv', delimiter=";")

In [4]:
df

                                                   Texto   Classe
0      SERVICO E LICENCAS DE SOFTWARE DE USO DO CALL CEN  M&E-SEC
1      UPGRADE DO SISTEMA DE SEGURANCA DO SITE ALEXANDRE  M&E-SEC
2      UPGRADE DO SISTEMA DE SEGURANCA DO SITE ALEXANDRE  M&E-SEC
3                            REFRIGERADOR 342 L FF CLEAN  OFF F&F
4                            REFRIGERADOR 342 L FF CLEAN  OFF F&F
...                                                  ...      ...
20312            2022 Aquisição de Analisador de Tamanho      AUC
20313            2022 Aquisição de Estantes para Área de      AUC
20314           2022 Aquisição de Equipamentos de Sonori      AUC
20315                                    2022 PC Refresh      AUC
20316           2022 Cobertura das Torres II e III e Dre      AUC

[20317 rows x 2 columns]

In [5]:
df["Classe"].unique()

array(['M&E-SEC', 'OFF F&F', 'DP-SW', 'DATAPROC', 'LAND', 'BLDG',
       'DP EQUIP', 'EQIP-MFG', 'OFF MACH', 'BLDGEQPT', 'AUTO T&T',
       'INT-TECR', 'AUC', 'EQIP-PLT', 'LHIMP', 'M&E-ELEC', 'LAB-ELEC',
       'AVEQUIP', 'BC-NLAB', 'DPNONERP', 'EQUIP-RD', 'PLT,JIGS', 'BC-LAB',
       'IND-BLDG', 'BD-IMPR', 'DP LEASE', 'DP-PBX', 'BD-SVSHV'],
      dtype=object)

In [6]:
categoria_map = {
    'IMOBILIARIO': ['LAND', 'IND-BLDG', 'BD-IMPR', 'DP LEASE', 'BD-SVSHV'],
    'MAQUINARIO': ['M&E-SEC', 'OFF MACH', 'M&E-ELEC', 'LAB-ELEC', 'AVEQUIP', 'EQUIP-RD', 'PLT,JIGS', 'OFF F&F', 'EQIP-PLT'],
    'SERVIÇOS': ['DP-SW', 'AUTO T&T', 'INT-TECR', 'AUC', 'LHIMP', 'BC-NLAB', 'DPNONERP', 'BC-LAB', 'DP-PBX', 'BLDG', 'BLDGEQPT'],
    'INFORMATICA': ['DATAPROC', 'DP EQUIP'],
    'MÓVEIS': ['EQIP-MFG', 'OFF F&F']
}

In [7]:
def classificar(classe):
    for categoria, valores in categoria_map.items():
        if classe in valores:
            return categoria
    return 'OUTROS'

# Aplicar a função de classificação ao DataFrame
df['Classe'] = df['Classe'].apply(classificar)

In [8]:
svm_classifier = SVC(probability=True, )
mlp_classifier = MLPClassifier()
decision_tree_classifier = DecisionTreeClassifier()
random_forest_classifier = RandomForestClassifier()
naive_bayes_classifier = MultinomialNB()

ensemble_classifier = VotingClassifier(estimators=[
    ('svm', svm_classifier),
    ('mlp', mlp_classifier),
    ('decision_tree', decision_tree_classifier),
    ('random_forest', random_forest_classifier),
    ('naive_bayes', naive_bayes_classifier),
], voting='soft')

In [9]:
stemmer = RSLPStemmer()
def preprocess_text(text):
    words = text.split()
    stemmed_words = [stemmer.stem(word) for word in words]
    processed_text = ' '.join([word for word in stemmed_words if word not in stop_words and len(word) > 1])
    return processed_text

In [10]:
df['Texto'] = df['Texto'].apply(preprocess_text)
X = df['Texto']
y = df['Classe']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
X_train

7276                                         adequ nr-12
19420                               iphon 12 black 128gb
2021     notebook mca lenov mod t420 seri 1s2537od4l1bf4
16919              "t14 standard us laptop (brazil), ba"
17403                 ipad air 4th wif 4g 64gb spac gray
                              ...
11284                 tub cpvc sch 80 ind 1.1/2 6mt tigr
11964                     esc 03 degrau aço inox aisi304
5390                      elev passag mca otil cap tonel
860                               kit cole motorol es400
15795         "thinkpad t480 standard: i5-8350u, 8gb me"
Name: Texto, Length: 16253, dtype: object

In [12]:
pipeline = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('classifier', ensemble_classifier)
])
pipeline.fit(X_train, y_train)
print(f'Score: {pipeline.score(X_test, y_test)}')

Score: 0.9402066929133859

In [13]:
pipeline.predict(["INSTALACAO AR CONDICIONADO - AREA AMONSTRAGEM"])

array(['MAQUINARIO'], dtype=object)

In [16]:
df2 = pd.read_csv('../data/Pfizer.csv', delimiter=";")
df2['Classe'] = df2['Classe'].apply(classificar)

In [19]:
df_test = pd.read_excel("../data/DATA_FULL.xlsx")
df_test.head()

                                               TEXTO
0                              MOTOR GE  NUMERAL  HP
1  SUBSTITUICAO DE DISCO DO CUBO DA CENTRI-FUGA  ...
2                         CABINE DE MCC  NUMERAL -DD
3                              REDUTOR DE VELOCIDADE
4                      VALVULA HITER  NUMERAL  PECAS

In [21]:
df_test.dropna(inplace=True)

In [22]:
df_test.shape

(435644, 1)

In [23]:
df_test["Classe"] = pipeline.predict(df_test["TEXTO"])

In [26]:
df_test.tail(20)

                                                    TEXTO      Classe
435642              CREDITO PIS/COFINS GARANTIR  NUMERAL     SERVIÇOS
435643   SUBESTACAO SE- NUMERAL - NUMERAL  C/ AREA PRIVAT  MAQUINARIO
435644            RATEIO GERENCIAMENTO SUBESTACAO DE AGUA    SERVIÇOS
435645           SISTEMA DETECCAO DE INCENDIO COMPLELEMEN  MAQUINARIO
435646             SISTEMA DETECCAO DE FUMACA COMPLEMENTO  MAQUINARIO
435647           COMPLEMENTO SISTEMA DETECCAO / ALARME DE  MAQUINARIO
435648           COMPLEMENTO SISTEMA DETECCAO / ALARME DE  MAQUINARIO
435649           COMPLEMENTO SISTEMA DETECCAO / ALARME DE  MAQUINARIO
435650           COMPLEMENTO SISTEMA DETECCAO / ALARME DE  MAQUINARIO
435651           COMPLEMENTO SISTEMA DETECCAO / ALARME DE  MAQUINARIO
435652           SISTEMA DETECCAO / ALARME DE INCENDIO SE  MAQUINARIO
435653     SISTEMA DE COMBATE A INCENDIO BOSH PS NUMERAL   MAQUINARIO
435654            COMLPEMENTO SUBESTACAO DE AGUA DE PROCE  MAQUINARIO
435655       SUBESTACAO DE AGUA DE PROCESSO SE- NUMERAL -  MAQUINARIO
435656  RATEIO GERENCIAMENTO  NUMERAL . NUMERAL  MTPS ...    SERVIÇOS
435657       SE- NUMERAL - NUMERAL   AMPLIACAO SUBESTACAO  MAQUINARIO
435658  SE- NUMERAL - NUMERAL  MELHORIA SUBESTACAO DE ...  MAQUINARIO
435659                   CREDITO PIS/COFINS S/IMOBILIZADO    SERVIÇOS
435660   MELHORIA SIST DE INCENDIO SE- NUMERAL - NUMERAL   MAQUINARIO
435661              CREDITO PIS/COFINS GARANTIR  NUMERAL     SERVIÇOS